name: Benchmark

on:
#   push:
#     branches: [ main ]
  workflow_dispatch:

jobs:
  Benchmark:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        include-prerelease: true
    - name: Benchmark
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git remote set-url --push origin https://sharpninja:${env:GITHUB_TOKEN}@github.com/gatewayprogrammingschool/Faslinq
        git fetch --unshallow
        git config user.email "ninja@thesharp.ninja"
        git config user.name "GitHub Actions"
        
        git checkout main
        
        .\bench.ps1 -Select -Once -Configuration Debug 
        
        # -Where -Take -TakeLast -First -FirstWhere -Last -LastWhere -Join -Configuration Configuration
        
        mv ./results.md ..
        
        git checkout gh-pages
        
        mv ../results.md ./benchmarks/results.md
        
        git add -v ./results.md

        git commit -m "Updated benchmark results."

        git push origin
        
